#!/usr/bin/env bash
# configuring apache to run on container

sudo apt-get update
sudo apt-get install apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo service apache2 restart
