#!/usr/bin/env bash
#debugging the issue with port 80 and nginx listening
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
