#!/usr/bin/env bash
# installing nginx

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
